mysiteS20/myapp/urls.py
from django.urls import path, re_path
from myapp import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView

app_name = 'myapp'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    #path(r'detail/<int:top_no>', views.detail, name='detail'),
    re_path(r'(?P<top_no>\d+)/', views.detail, {}, name='detail'),
    path(r'courses/', views.courses, name='courses'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'order_response/', views.place_order, name='place_order'),
    path(r'courses/<int:course_id>', views.coursedetail, name='course_detail'),
    path(r'login', views.user_login, name='login'),
    path(r'logout', views.user_logout, name='logout'),
    path(r'myaccount', views.myaccount, name='myaccount'),
    path(r'register', views.register, name='register'),
    # path(r'reset-password/', PasswordResetView.as_view(), name='reset_password'),
    # path(r'reset-password/done/', PasswordResetDoneView.as_view, name='password_reset_done'),
    # path(r'password_reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view,
    #      name='password_reset_confirm')
]

mysiteS20/mysiteS20/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include

urlpatterns = [
    path(r'myapp/', include('myapp.urls')),
    path(r'admin/', admin.site.urls),
path('myapp/password_reset/',auth_views.PasswordResetView.as_view(template_name='admin/registration/password_reset_form.html'),name='password_reset'),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='admin/registration/password_reset_done.html'),
         name='password_reset_done'), path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="admin/registration/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='admin/registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

mysiteS20/myapp/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class Topic(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200, null=True)

    def __str__(self):
        return '{ Name: ' + self.name + \
               '; Category: ' + self.category + ' }'


def validate_limit(value):
    if not 100 <= value <= 200:
        raise ValidationError(('Please enter value between 100 and 200 , %(value)  is not in the defined range '),
                              params={'value': value}, )


class Course(models.Model):
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[validate_limit])
    hours = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    interested = models.PositiveIntegerField(default=1)
    stages = models.PositiveIntegerField(default=3)

    def discount(self):
        return float(self.price) * 0.9

    def __str__(self):
        return '{ Name: ' + self.name + \
               '; Price: ' + str(self.price) + \
               '; For Everyone: ' + str(self.for_everyone) + \
               '; Topic: ' + self.topic.name + \
               '; Description: ' + (self.description or 'NA') + '} '


class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'),
    ('CG', 'Calgery'),
    ('MR', 'Montreal'),
    ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    interested_in = models.ManyToManyField(Topic)

    def __str__(self):
        return '{ Name: ' + self.first_name + ' ' + self.last_name + \
               '; School: ' + self.school + \
               '; City: ' + self.city + \
               '; Interested in: ' + str(self.interested_in.values_list('name')) + '} '


class Order(models.Model):
    ORDER_STATUS_CHOICES = [(0, 'Cancelled'), (1, 'Order Confirmed')]
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, related_name='student', on_delete=models.CASCADE, max_length=200)
    levels = models.PositiveIntegerField(default=0)
    order_status = models.IntegerField(choices=ORDER_STATUS_CHOICES, default=1)
    order_date = models.DateField(default=datetime.date.today)

    def total_cost(self):
        return sum(course.price for course in self.course.all())

    def __str__(self):
        return '{ Student: ' + self.student.first_name + ' ' + self.student.last_name + \
               '; Courses: ' + self.course.name + \
               '; Levels: ' + str(self.levels) + \
               '; Order Status: ' + str(self.order_status) + \
               '; Order Date: ' + str(self.order_date) + '}'

mysiteS20/myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import CheckboxSelectMultiple, PasswordInput
from myapp.models import Order, Student
from passlib.ifc import PasswordHash


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['student', 'course', 'levels', 'order_date']
        widgets = {
            'student': forms.RadioSelect,
            'order_date': forms.SelectDateWidget(attrs={'class': 'years=date.today()'},
                                                 empty_label=("Year", "Month", "Day"))
        }
        labels = {
            'student': 'Student Name',
            'order_date': 'Order Date'
        }


class InterestForm(forms.Form):
    interested = forms.ChoiceField(widget=forms.RadioSelect(), choices=[('1', 'Yes'), ('0', 'No')])
    levels = forms.IntegerField(initial=1)
    comments = forms.CharField(widget=forms.Textarea, label='Additional Comments', required=False)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        # do not require password confirmation
        del self.fields['password2']

    class Meta:
        model = Student
        fields = ['username', 'first_name', 'last_name', 'city', 'interested_in']

        widgets = {
            'interested_in': forms.CheckboxSelectMultiple,
        }

        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'interested_in': 'Interested In'
        }

mysiteS20/myapp/views.py
import datetime
from urllib.parse import urlencode

from django.shortcuts import render, get_object_or_404, redirect

from django.http import HttpResponse, HttpResponseRedirect
from myapp.forms import OrderForm, InterestForm, LoginForm, RegisterForm
from .models import Topic, Course, Student, Order
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def index(request):
    # top_list = Topic.objects.all().order_by('id')[:10]
    top_list = Topic.objects.all().order_by('id')[:10]
    last_login = request.session['last_login'] if 'last_login' in request.session else 'Your last login was more than one hour ago'
    return render(request, "myapp/index.html", {'top_list': top_list, 'last_login': last_login})


def about(request):
    # response = HttpResponse()
    # para = '<p>' + 'This is an E-learning Website! Search our Topics to find all available Courses.' + '</p>'
    # response.write(para)
    if 'about_visits' in request.session:
        request.session['about_visits'] += 1
        request.session.set_expiry(300)
    else:
        request.session['about_visits'] = 1
    return render(request, "myapp/about.html", {'number_of_visits': request.session['about_visits']})


def detail(request, top_no):
    # response = HttpResponse()
    # topic  = Topic.objects.get(id=top_no)
    topic = get_object_or_404(Topic, id=top_no)  # Gives 404 if Topic not found
    course_list = Course.objects.filter(topic__id=top_no)
    # response.write(topic)
    # response.write('<p>' + Course List: ' + '</p>')
    # for course in Course.objects.filter(topic__id=top_no):
    #     if course.for_everyone:
    #         for_str = "This Course is For Everyone!"
    #     else:
    #         for_str = "This Course is not For Everyone!"
    #     response.write('<p>' + str(course.id) + ': ' + str(course) + for_str + '</p>')
    # return response
    return render(request, "myapp/detail.html", {'topic': topic, 'course_list': course_list})


def courses(request):
    courselist = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'courselist': courselist})


def place_order(request):
    msg = ''
    courselist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            print(order)
            if order.levels <= order.course.stages:
                form.save()
                msg = 'Your course has been ordered successfully.'
                if float(order.course.price) > 150:
                    order.course.discounted_price = Course.discount(order.course)
                    order.course.save()
                    msg = msg + 'Price for order updated to $' + str(order.course.discounted_price)
            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
        return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'courselist': courselist})


def coursedetail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            # request.POST.get('interested') is '1'
            if form.cleaned_data['interested'] == '1':
                course.interested = course.interested + 1
                course.save()
            return index(request)
    else:
        # if a GET (or any other method) we'll create a blank form
        form = InterestForm()
    return render(request, 'myapp/coursedetail.html', {'form': form, 'course': course})


def user_login(request):
    context = {}
    context['form'] = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = str(datetime.datetime.now())
                # request.session.set_expiry(3600)
                if 'next' in request.POST:
                    return redirect('myapp:' + request.POST.get('next'))
                return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html', context)


@login_required
def user_logout(request):
    request.session.clear()
    #logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


def myaccount(request):
    if request.user.is_authenticated:
        current_user = request.user

        if Student.objects.filter(pk=current_user.id):
            first_name = current_user.first_name
            last_name = current_user.last_name
            ordered_course = Order.objects.filter(student_id=current_user.id).values_list('course__name', flat=True)
            interested = Student.objects.filter(id=current_user.id).values_list('interested_in__courses__name', flat=True)
            return render(request, 'myapp/myaccount.html',
                          {'ordered_course': ordered_course, 'first_name': first_name, 'last_name': last_name,
                           'interested': interested})
        else:
            return HttpResponse('You are not a registered student!')
    else:
        base_url = reverse('myapp:login')
        query_string = urlencode({'next': 'myaccount'})
        url = '{}?{}'.format(base_url, query_string)
        return redirect(url)


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myapp:login')

    form = RegisterForm()
    return render(request, 'myapp/register.html', {'form': form})

mysiteS20/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}About{% endblock %}
{% block body_block %}
    <p>'This is an E-learning Website! Search our Topics to find all available Courses.</p>
    <p>You have visited {{ number_of_visits }} times.</p>
{% endblock %}

mysiteS20/myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
    <p>'This is an E-learning Website! Search our Topics to find all available Courses.</p>
    <p><a href={% url 'myapp:index' %}>Home page</a></p>
</body>
</html>

mysiteS20/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
    <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
<div>
    <h1>Hello
        {% block myhdg %}
            {% if request.user.is_authenticated %} {{ user.first_name }} {{ user.last_name }}
            {% else %} User {% endif %}
        {% endblock %}
    </h1>
    {% block body_block %}*** {% endblock %}
</div>
<hr/>
<div>
    <ul>
        {% if request.user.is_authenticated %}
            <li ><a href="{% url 'myapp:logout' %}">Logout</a></li>
            <li ><a href="{% url 'myapp:myaccount' %}">My Account</a></li>
        {% else %}
            <li ><a href="{% url 'myapp:login' %}">Login</a></li>
            <li ><a href="{% url 'myapp:register' %}">Register <Here></Here></a></li>
        {% endif %}
        <p></p>
        <li class="hbar1"><a href="{% url 'myapp:about' %}">Find out about our ELearning site</a></li>
        <li class="hbar1"><a href="{% url 'myapp:index' %}">Click here to
            return to main page</a><br/></li>
        <li class="hbar1"><a href="{% url 'myapp:courses' %}">Click here to view courses</a><br/></li>
    </ul>
</div>
</body>
</html>

mysiteS20/myapp/templates/myapp/coursedetail.html
{% extends 'myapp/base.html' %}
{% block title %}
    Course Details
{% endblock %}
{% block body_block %}
    <h3>Course name: {{ course.name }} {{ a }}</h3>
    <p class="paragraphs"> Number of people interested : {{ course.interested }} </p>
    <p class="paragraphs"> Price : {{ course.price }}</p>
    {% if not course.for_everyone %}
        <strong>This course is not for everyone.</strong>
    {% endif %}
    <p class="paragraphs"> Indicate your interest in the course</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

mysiteS20/myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}
{% block title %}Courses{% endblock %}
{% block body_block %}
    {% if courselist %}
        <ol>
            {% for course in courselist %}
                <li><a href="{% url 'myapp:courses' %}{{ course.id }}">{{ course.name }} </a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}
    <p class="paragraphs"><a href="{% url 'myapp:place_order' %}">Place an order</a></p>
{% endblock %}

mysiteS20/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}Detail{% endblock %}
{% block body_block %}
    <h2>Topic details: {{ topic.name }}</h2>
    <p>Category: {{ topic.category }}</p>
    <p>Course List: </p>
    <ol>
        {% for course in course_list %}
            <li> {{ course.name }} - ${{ course.price }} </li>
        {% endfor %}
    </ol>
{% endblock %}

mysiteS20/myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
    <h2>Topic details: {{ topic.name }}</h2>
    <p>Category: {{ topic.category }}</p>
    <p>Course List: </p>
    <ol>
        {% for course in course_list %}
            <li> {{ course.name }} - ${{ course.price }} </li>
        {% endfor %}
    </ol>

    <p><a href={% url 'myapp:index' %}>Home page</a></p>
</body>
</html>

mysiteS20/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block title %}Main{% endblock %}
{% block body_block %}
    <h3>Your last login time is : {{last_login}}</h3>
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top in top_list %}
                <li><a href={% url 'myapp:index' %}{{ top.id }}> {{ top.name }} </a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
{% endblock %}

mysiteS20/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top in top_list %}
                <li><a href={% url 'myapp:index' %}{{ top.id }}> {{ top.name }} </a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}

    <p><a href={% url 'myapp:about' %}>About page</a></p>
</body>
</html>

mysiteS20/myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% block title %}Login{% endblock %}
{% block body_block %}

    <form action="" method="post">
    {% csrf_token %}
         {{ form.as_p }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
    <input type="submit" value="Login"/>
    <a href="{%  url 'password_reset' %}"> Forgot Password?</a>
    </form>
{% endblock %}

mysiteS20/myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}
{% block title %}Main{% endblock %}
{% block body_block %}
    <h3>First Name: {{ first_name }} </h3>
    <h3>Last Name: {{ last_name }}</h3>
    <h3>Courses Ordered:</h3>
    <ol>
        {% for i in ordered_course %}
            <li> {{ i }} </li>
        {% endfor %}
    </ol>

    <h3>Topics Interested In:</h3>
    <ol>
        {% for interest in interested %}
            <li> {{ interest }} </li>
        {% endfor %}
    </ol>

{% endblock %}

mysiteS20/myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block title %}Order Placed{% endblock %}
{% block body_block %}
    {% csrf_token %}
    <p> {{ msg }}</p>
{% endblock %}

mysiteS20/myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block title %}Order{% endblock %}
{% block body_block %}
    <p>Course List: </p>
    <ol>
        {% for course in courselist %}
            <li>{{ course.name }} - ${{ course.price }}</li>
        {% endfor %}
    </ol>
    <p>Order here:</p>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
    <p> {{ msg }}</p>
{% endblock %}

mysiteS20/myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block title %}Register{% endblock %}
{% block body_block %}
    <form action="" method="post">
    {% csrf_token %}
         {{ form.as_p }}
    <input type="submit" value="Register"/>
    </form>
{% endblock %}